### ISSUE TITLE
how to use without a sanity client (for example, with gatsby-source-sanity)

### ISSUE THREAD

**Issue by dylanjha** [sanity-io/image-url#2]
When using gatsby-source-sanity, I don't typically have access to a sanityClient directly, but I do have access to a sanity image `asset` object via the graphql api that the gatsby-source-sanity exposes.

The builder in this example requires a configured sanity client, is there a way to get the convenience of using the builder methods, by passing in a raw sanity asset that was obtained in a gatsby build?

```
const builder = imageUrlBuilder(myConfiguredSanityClient)
```

**Comment by rexxars** [comment]
You can use `imageUrlBuilder({projectId: 'abc123', dataset: 'someDataset'})` if you know the project ID and dataset up front.

I _suppose_ you could also extract the project ID and dataset from an asset by looking at the `path` property and doing some parsing, but that only works if the asset is the _document_ and won't work if it's a reference

**Comment by dylanjha** [comment]
sweet, thank you!
