### ISSUE TITLE
AVIF Image Format Support 

### ISSUE THREAD

**Issue by iankduffy** [sanity-io/image-url#26]
Wondering if there are plans for AVIF Image Format Support for sanity images (https://jakearchibald.com/2020/avif-has-landed/) at the moment I have auto format on which in chrome 85, is getting webp images but this could be a AVIF image meaning even smaller images file size to be loaded on the site, in terms of web performance.

**Comment by peterskogsberg** [comment]
This would indeed be great, but I suspect from this library's perspective it'd just be the same `auto=format` parameter added, indicating that client accepts any supported format.

**Comment by piersolenski** [comment]
Now that this has dropped in Chrome and Firefox, as well as Gatsby adding support https://github.com/gatsbyjs/gatsby/pull/28742 - it'd be great to see Sanity supporting it too!

**Comment by rexxars** [comment]
It's coming, but there are a number of considerations given it's a very costly format to encode (10-15x that of JPEG/WebP). We're eager to deliver, but we want to make sure we get it right :)

**Comment by mrgnou** [comment]
Is there any plan to support it someday or has this idea been abandoned?

**Comment by fmoessle** [comment]
Any updates? Would love to see AVIF support <3

**Comment by Kyoss79** [comment]
The [documentation](https://www.sanity.io/docs/image-urls#auto-777d41f23d56) says:

> [q](https://www.sanity.io/docs/image-urls#q-83311ae15535)
integer
Quality 0-100. Specify the compression quality (where applicable). Defaults are 75 for JPG and WebP and 55 for AVIF.

So maybe it's here already? Can anyone confirm? Thinking about switching to sanity.

**Comment by mrgnou** [comment]
> The [documentation](https://www.sanity.io/docs/image-urls#auto-777d41f23d56) says:
> 
> > [q](https://www.sanity.io/docs/image-urls#q-83311ae15535)
> > integer
> > Quality 0-100. Specify the compression quality (where applicable). Defaults are 75 for JPG and WebP and 55 for AVIF.
> 
> So maybe it's here already? Can anyone confirm? Thinking about switching to sanity.

autoformat still delivers webp, no sign of avif yet.

**Comment by 3backup** [comment]
Any update there?

**Comment by stephenhmarsh** [comment]
+1 we want avif! 👏 we want avif! 👏

**Comment by peterskogsberg** [comment]
...or are we skipping a format generation and going directly to JpegXL? 

Seriously, it's been 20 months since
_"We're eager to deliver"._

**Comment by HuyAms** [comment]
I love to see AVIF too

**Comment by leo-cheron** [comment]
Almost 3 years later, this standard is still missing :(

**Comment by ps-kate** [comment]
Any updates here?

**Comment by fmoessle** [comment]
Any news?

**Comment by presto2116** [comment]
went searching for AVIF options with sanity, stumbled upon this issue. 3 years and no updates. 😢

**Comment by zabatonni** [comment]
+1 avif is a must

**Comment by ahdrage** [comment]
Ode to Sanity, Thou Art Most Fair

In realms of code where Sanity doth reign,
A platform vast, where structured data’s kept,
A wondrous tool that doth developers gain,
Yet one great woe hath countless eyes e’er wept.

Four years and more, a promise once was made,
To bring forth AVIF in all its grace,
Yet still we wait, in hope’s long shadow laid,
With eager hearts and tear-streaked, weary face.

Oh, Sanity, thy features rich and bright,
Have brought us joy in many varied ways,
Thou art a beacon in the coding night,
But here we languish, longing for the days.

For AVIF, that format sleek and new,
Could make thy splendor even more complete,
Tens of developers, their tears like dew,
Cry out for thee, with voices bittersweet.

Imagine then, a world where all is right,
Where AVIF doth dance within thy frame,
A place where joy and peace would reunite,
And Sanity would earn yet greater fame.

So hark, ye builders of this mighty tool,
To heed the pleas of those who love thee well,
For once this gap is bridged, our hearts may cool,
And in thy triumph, future stories tell.

Then let the world, with Sanity's embrace,
Rejoice in harmony, both near and far,
As AVIF finds its rightful place,
And makes thee brighter than the morning star.

**Comment by bobinska-dev** [comment]
After we received this awesome poem we had to have another discussion and added this to our roadmap. We are aiming for Q1 next year 🙌

**Comment by ciruz** [comment]
Hey,

We are currently experiencing a Chromium bug (see: https://issues.chromium.org/issues/350944650) where images don't render correctly with Next.js and next/image. It's notable that the bug example also involves `Next.js` and `Sanity`, similar to our setup.

The only available workaround right now is to convert all images to the AVIF format (see: https://issues.chromium.org/issues/350944650#comment9).

Since we are affected by this issue and use Sanity as our CMS, we would like to switch to AVIF for all our images as a temporary fix.

**Comment by patrulea** [comment]
please make this happen 🙏

**Comment by rexxars** [comment]
Hello everyone!
You can now help us out by participating in the AVIF beta program: https://www.sanity.io/help/avif

**Comment by iankduffy** [comment]
> Hello everyone! You can now help us out by participating in the AVIF beta program: https://www.sanity.io/help/avif

Thank you so much for updating on this old issue, will give it a trial. Is there a main github discussion on beta feedback.

**Comment by rexxars** [comment]
> Is there a main github discussion on beta feedback.

Not currently, we are not expecting this to be in beta long before gradually rolling it out. Feel free to provide feedback to `avif@sanity.io` and/or in this issue.

**Comment by kmelve** [comment]
> Oh joyous day, the wait is finally done,
> AVIF arrives, a new age has begun.
> No more the tears, the longing or the pain,
> As Sanity's embrace doth AVIF gain.

[We have rolled out AVIF support for image transformations out in production for everyone!](https://www.sanity.io/blog/launching-avif-support)
