### ISSUE TITLE
Server and Client urls don't match

### ISSUE THREAD

**Issue by mikeyrayvon** [sanity-io/image-url#33]
I'm using `createImageUrlBuilder` from [next-sanity](https://github.com/sanity-io/next-sanity/blob/main/src/imageUrlBuilder.ts)

```
// utils/sanity.js

const config = {
  dataset: process.env.SANITY_STUDIO_API_DATASET,
  projectId: process.env.SANITY_STUDIO_API_PROJECT_ID,
}

export const urlFor = source => createImageUrlBuilder(config).image(source)

```

```
// components/Component.js

import { urlFor } from 'utils/sanity'

const Component = ({ data }) => {
  if (!data)
    return null
  
  return (
    <div style={{backgroundImage: `url(${urlFor(data.image).url()})`}}></div>
  )
}

export default Component
```
and I'm getting the following error in the browser console
```
Warning: Prop `style` did not match. 
Server: "background-image:url(https://cdn.sanity.io/images/myProjectId/staging/43ba14c69f28b68478f5badebaa849e6038b494f-512x512.png?w=400)" 
Client: "background-image:url(https://cdn.sanity.io/images/undefined/undefined/43ba14c69f28b68478f5badebaa849e6038b494f-512x512.png?w=400)"
```
The image renders, but I'm uncertain as to why this error is logging. Any advice? Thank you!

**Comment by rexxars** [comment]
`SANITY_STUDIO_API_DATASET` is not exposed in next.js applications - environment variables needs to be prefixed with `NEXT_PUBLIC_`, so you'll need to use something like `NEXT_PUBLIC_SANITY_PROJECT_ID` and ``NEXT_PUBLIC_SANITY_DATASET` (and make sure those are defined in your environment variables).
