### ISSUE TITLE
ImageUrlBuilder should ignore transformation on gif/svg assets by default

### ISSUE THREAD

**Issue by xiata** [sanity-io/image-url#35]
Per https://www.sanity.io/docs/assets#644f57e96542

> GIF and SVG pass through the image pipeline untouched, but if you want them scaled they will need to be output as one of the three formats above.

cdn.sanity.io's handling of `auto=format` on gif images makes no sense and is a foot-gun. Even if it decides one of the three supported formats, the most common use-case for a gif is an animated gif, which precludes png and jpg formats most of the time. This leads to `webp` being the only potential format for this image type that makes any sense, **but when it is chosen, the transformation only outputs the first frame of an animated gif, discarding the rest.** This is a seriously unexpected behavior for most people. It's understandable though, because it's extremely expensive to transform an animated gif to webp, but not an acceptable behavior nevertheless.

**Note that both gif and svg formats support animation, so transformations in general to them are dangerous.**

This package is an accomplice to this bad behavior. Because `ImageUrlBuilder` is often used in where not much context is known other than "here is an `imageObject`", such as a general `image` type renderer used with @sanity/block-content-to-react, if the user has code to generate a URL add `.auto('format')` their `ImageUrlBuilder` object inside their `image` renderer, there is no nice way of avoiding this cdn trap without doing hideous inspection of the `imageObject.asset._ref` (or the dereferenced image `imageObject.asset`). Note that other transformation functions may inflict the same problem-- animated images no longer animating. Just in my specific case, I found `&auto=format` always breaks animated gifs.

By default, when a passed in object to `imageObject` is a gif (or svg image), it should ignore all image transformations because it risks breaking the potentially animated image unintentionally. I imagine some heuristics can be smarter than a blanket ban, e.g. a svg/gif with `&format=jpg` which could be a valid transformation, but it increases mental load for developers, so I'd prefer it to be gated so I know I'm about to do something dangerous instead of firing the CS-ticket gun at me later unexpectedly. 

With that said...

React lets you do potentially broken things with things like `dangerouslySetInnerHTML`. This library should do the same for gif/svg files. If they want to transform gif/svg assets, it's probably wise to make it a opt-in behavior where they need to`.dangerouslyTransform('gif', 'svg')` before any transformation option will be used for blacklisted file types (silently ignore in production, warn once in development mode). This prevents the foot-gun from affecting most users, and respecting existing documentation that states that gifs won't be affected, while keeping their code easy to use. And those who do need transform gif/svg images, it serves as a warning for all other developers looking at the code: "danger, here be dragons".

I noticed this because my ImageUrlBuilder wrapping function that is used heavily throughout my application got inconsistent image type results (sometimes gif, sometimes webp), where any time a webp result was loaded, the animated gif would not animate. This was especially visible for `<= iOS 14.4` and `Safari 14` user agents. Safari 14 supports `webp`, which brought this issue to our attention.

Of course, if the cdn is fixed so transforming gifs/svgs return properly animated webp images that has the animations applied, it would be acceptable. Being able to do that on the fly seems iffy though because video transforms are slow and would be a horror show if someone decided to DoS by mass requesting with random transformation parameters (if there aren't already some protection in place to 429 them). A good use case for a 303 response though with the first frame of an animated image though until the animated image is fully processed.

**Comment by rexxars** [comment]
Thanks for reporting, and apologies for this - we were testing a new version of our image pipeline on a subset of our servers, and this behavior (unintentionally) differed from the previous version. We've written tests for the regression, implemented a fix and rolled it out into production - we're now invalidating the cache for all projects, but there might still be cached versions in browsers, unfortunately.
