### ISSUE TITLE
Gif image not being transformed

### ISSUE THREAD

**Issue by bplmp** [sanity-io/image-url#37]
I have a gif image and it's not being transformed by Sanity: <https://cdn.sanity.io/images/n2jhvipv/production/17cb02d8328fa43018176a871a175cbcacc61b98-1650x950.gif?w=600&h=600&fit=crop&crop=center&auto=format>

![Untransformed image](https://cdn.sanity.io/images/n2jhvipv/production/17cb02d8328fa43018176a871a175cbcacc61b98-1650x950.gif?w=600&h=600&fit=crop&crop=center&auto=format)

I expected the image to be 600x600 px and cropped, but it is not.

On the same website, other images that are jpg are working though: <https://cdn.sanity.io/images/n2jhvipv/production/cb0f7e793eeb44e9ce010a7a3efe8731bc444e0a-601x600.jpg?w=600&h=600&fit=crop&crop=center&auto=format>

![Transformed image](https://cdn.sanity.io/images/n2jhvipv/production/cb0f7e793eeb44e9ce010a7a3efe8731bc444e0a-601x600.jpg?w=600&h=600&fit=crop&crop=center&auto=format)

I wonder, is this by design? I saw this issue but wasn't sure what was the change you have implemented: https://github.com/sanity-io/image-url/issues/35

How can I make the transformation work for gif images too?

**Comment by rexxars** [comment]
This is by design - gifs are not transformed: https://www.sanity.io/docs/assets#644f57e96542

> GIF and SVG pass through the image pipeline untouched, but if you want them scaled they will need to be output as one of the three formats above.

This is mostly due to not supporting animated gifs, but currently also applies for non-animated gifs.
