### ISSUE TITLE
Export the ImageUrlBuilder type

### ISSUE THREAD

**Issue by Svish** [sanity-io/image-url#5]
Wanted to accept an `ImageUrlBuilder` as a prop in a component, but the type isn't exported, as far as I can see. 😟

Like, I can "see" it via my IDE, but since it's not exported, I can't actually use it as a prop or function parameter type. 😕

Please export the `ImageUrlBuilder` type?

**Comment by Svish** [comment]
Worked around it as follows, but really shouldn't be necessary working around this. Should just be an exported type from the library.

```ts
import imageUrlBuilder from '@sanity/image-url';
type ImageUrlBuilder = ReturnType<typeof imageUrlBuilder>;
```

**Comment by rexxars** [comment]
Could you see if 0.140.16 fixes your problem?

**Comment by Svish** [comment]
@rexxars Looking at the diff for that version I assume it will, but checking now (if only my slow connection could hurry up) to be sure. Will close the issue when verified. 👍

**Comment by Svish** [comment]
Yep, I can use the type in my code now:

```ts
import React from 'react';
import { ImageUrlBuilder } from '@sanity/image-url/lib/types/builder';

interface ImageProps extends Omit<React.HTMLProps<HTMLImageElement>, 'src'> {
  src: string | ImageUrlBuilder;
}

export default function Image(props: ImageProps) {
  if (typeof props.src !== 'string') {
    props.src = props.src.url()!;
  }

  // ...
}
```

👍
