### ISSUE TITLE
TypeError: __vite_ssr_import_2__.default is not a function

### ISSUE THREAD

**Issue by octave** [sanity-io/image-url#71]
I'm using `@sanity/image-url@1.1.0`, in a `@shopify/hydrogen@2024.10.0` app with `hydrogen-sanity@4.3.0`.

I'm currently having errors showing in the console (both server side and client side):

```powershell
TypeError: __vite_ssr_import_2__.default is not a function
    at SanityImage (/app/components/media/SanityImage.tsx:103:22)
``` 
This is line 103:

```typescript
const urlBuilder = imageUrlBuilder({
    projectId: sanityProjectID,
    dataset: sanityDataset,
  })
    .image({
      _ref: src,
      crop,
      hotspot,
    })
    .auto('format');
``` 

The errors are not breaking, and the images are showing fine, which makes it hard to debug.

**Comment by martin-lacko-rebood** [comment]
Same issue, did you manage to find some solution?

**Comment by octave** [comment]
@martin-lacko-rebood I did today! You just have to add the package to the `vite.config.ts` file under the `optimizeDeps`, like this:

```javascript
  ssr: {
    optimizeDeps: {
      include: [
        '@sanity/image-url',
      ],
    },
  },
```

**Comment by martin-lacko-rebood** [comment]
@octave awesome, works! Thank you!
